import { Achievement, GameStats } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_win',
    title: 'Pemula',
    description: 'Selesaikan puzzle pertama kamu',
    icon: '🎯',
    unlocked: false,
    condition: (stats: GameStats) => stats.gamesCompleted >= 1,
  },
  {
    id: 'speed_demon',
    title: 'Kilat',
    description: 'Selesaikan puzzle dalam waktu kurang dari 2 menit',
    icon: '⚡',
    unlocked: false,
    condition: (stats: GameStats) => stats.fastestTime > 0 && stats.fastestTime <= 120,
  },
  {
    id: 'perfect_game',
    title: 'Sempurna',
    description: 'Selesaikan puzzle tanpa menggunakan hint',
    icon: '💎',
    unlocked: false,
    condition: (stats: GameStats) => stats.perfectGames >= 1,
  },
  {
    id: 'streak_5',
    title: 'On Fire',
    description: 'Menangkan 5 game berturut-turut',
    icon: '🔥',
    unlocked: false,
    condition: (stats: GameStats) => stats.currentStreak >= 5,
  },
  {
    id: 'master_easy',
    title: 'Master Mudah',
    description: 'Selesaikan 10 puzzle level mudah',
    icon: '🌟',
    unlocked: false,
    condition: (stats: GameStats) => stats.easyCompleted >= 10,
  },
  {
    id: 'master_medium',
    title: 'Master Sedang',
    description: 'Selesaikan 10 puzzle level sedang',
    icon: '⭐',
    unlocked: false,
    condition: (stats: GameStats) => stats.mediumCompleted >= 10,
  },
  {
    id: 'master_hard',
    title: 'Master Sulit',
    description: 'Selesaikan 10 puzzle level sulit',
    icon: '🏆',
    unlocked: false,
    condition: (stats: GameStats) => stats.hardCompleted >= 10,
  },
  {
    id: 'dedicated',
    title: 'Berdedikasi',
    description: 'Mainkan 50 game',
    icon: '🎮',
    unlocked: false,
    condition: (stats: GameStats) => stats.gamesPlayed >= 50,
  },
  {
    id: 'math_genius',
    title: 'Jenius Matematika',
    description: 'Raih total score 10,000',
    icon: '🧠',
    unlocked: false,
    condition: (stats: GameStats) => stats.totalScore >= 10000,
  },
  {
    id: 'unstoppable',
    title: 'Tak Terhentikan',
    description: 'Menangkan 10 game berturut-turut',
    icon: '👑',
    unlocked: false,
    condition: (stats: GameStats) => stats.longestStreak >= 10,
  },
];